version: '3.8'

services:
  db:
    image: supabase/postgres:15.3.0
    container_name: supabase_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - db
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
